---
title: "Day 2: I Was Told There Would Be No Math"
---

[Reference](https://adventofcode.com/2015/day/2)

```{r}
#| label: 2015 - day 2 - load data

library(tidyverse)

input <- read_csv(file = "inputs/2015/02.txt", col_names = "original")
```

## Part One

::: {.panel-tabset}

## Solution

```{r}
#| label: 2015 - day 2 - part 1

paper_area <- function(l, w, h) {
    2L * (l*w + w*h + h*l) + min(l*w, w*h, h*l)
}

paper <- input |> 

    separate_wider_delim(cols        = original,
                         names       = c("l", "w", "h"),
                         delim       = "x",
                         cols_remove = FALSE) |> 

    mutate(across(.cols = c(l, w, h), .fns = as.integer)) |> 

    mutate(paper = pmap_int(.l = list(l, w, h), .f = paper_area))

paper |> 
    summarise(total_paper = sum(paper)) |> 
    pull(total_paper) |> 
    cat()
```

## Full Table

```{r}
#| label: 2015 - day 2 - pat 1 full table
#| echo: false

rmarkdown::paged_table(paper)
```

:::

## Part Two

::: {.panel-tabset}

## Solution

```{r}
#| label: 2015 - day 2 - part 2

ribbon_length <- function(l, w, h) {
    2L * (l+w+h - max(l, w, h)) + l*w*h
}

paper <- paper |>
    mutate(ribbon = pmap_int(.l = list(l, w, h), .f = ribbon_length))

paper |> 
    summarise(total_ribbon = sum(ribbon)) |> 
    pull(total_ribbon) |> 
    cat()
```

## Full Table

```{r}
#| label: 2015 - day 2 - pat 2 full table
#| echo: false

rmarkdown::paged_table(paper)
```

:::
