---
title: "Day 4: The Ideal Stocking Stuffer"
---

[Reference](https://adventofcode.com/2015/day/4)

```{r}
#| label: 2015 - day 4 - load data

library(tidyverse)
library(digest)

input <- "bgvyzdsv"
```

::: {.panel-tabset}

## `digest()` tests

```{r}
#| label: 2015 - day 4 - md5 function tests

# example 1
digest(str_c("abcdef", 609043), algo = "md5", serialize = FALSE)

# example 2
digest(str_c("pqrstuv", 1048970), algo = "md5", serialize = FALSE)
```

## Note

::: {.callout-note}
I learned how to evaluate MD5 hash in R using the `digest` package from
[here](https://emilhvitfeldt.github.io/rstats-adventofcode/2015.html?panelset=day-4).
:::

:::

## Part One

::: {.panel-tabset}

## Solution

```{r}
#| label: 2015 - day 4 - part 1

n <- 255000 # Empirically sufficient to find the answer

md5_hashes <- tibble(
    number = 1:n,
    string = str_c(input, number),
    hash = map_chr(string, \(x) digest(x, algo = "md5", serialize = FALSE))
)

lowest_number <- md5_hashes |> 
    filter(str_starts(hash, "00000")) |> 
    slice(1) |>
    pull(number)

cat("Lowest number with 5 leading zeros:", lowest_number, "\n")
```

## Partial Table

```{r}
#| label: 2015 - day 4 - part 1 partial table
#| echo: false

md5_hashes |> 
    slice(254571:254580) |> 
    rmarkdown::paged_table()
```

:::

## Part Two

::: {.panel-tabset}

## Solution

```{r}
#| label: 2015 - day 4 - part 2

n <- 1040000 # Empirically sufficient to find the answer

md5_hashes <- tibble(
    number = 1:n,
    string = str_c(input, number),
    hash = map_chr(string, \(x) digest(x, algo = "md5", serialize = FALSE)) 
)

lowest_number <- md5_hashes |> 
    filter(str_starts(hash, "000000")) |> 
    slice(1) |>
    pull(number)

cat("Lowest number with 6 leading zeros:", lowest_number, "\n")
```

## Partial Table

```{r}
#| label: 2015 - day 4 - part 2 partial table
#| echo: false

md5_hashes |> 
    slice(1038731:1038740) |> 
    rmarkdown::paged_table()
```

:::
