---
title: "Day 5: Doesn't He Have Intern-Elves For This?"
---

[Reference](https://adventofcode.com/2015/day/5)

```{r}
#| label: 2015 - day 5 - load data

library(tidyverse)

input <- read_csv(file = "inputs/2015/05.txt", col_names = "original")
```

## Part One

::: {.panel-tabset}

## Solution

```{r}
#| label: 2015 - day 5 - part 1

has_3more_vowels <- function(string) {
    str_count(string = string, pattern = "[aeiou]") >= 3
}

has_1more_double <- function(string) {
    str_count(string = string, pattern = "([a-z])\\1") >= 1
}

has_not_ab_cd_pq_xy <- function(string) {
    !str_detect(string = string, pattern = "ab|cd|pq|xy")
}

is_nice <- function(string) {
    has_3more_vowels(string) &
    has_1more_double(string) &
    has_not_ab_cd_pq_xy(string)
}

nice <- input |> 
    mutate(three_more_vowels = map_lgl(.x = original, .f = has_3more_vowels),
           one_more_double   = map_lgl(.x = original, .f = has_1more_double),
           not_ab_cd_pq_xy   = map_lgl(.x = original, .f = has_not_ab_cd_pq_xy),
           nice              = map_lgl(.x = original, .f = is_nice))

nice |> 
    summarise(total_nice = sum(nice)) |> 
    pull(total_nice) |> 
    cat()
```

## Full Table

```{r}
#| label: 2015 - day 5 - part 1 full table
#| echo: false

rmarkdown::paged_table(nice)
```

:::

## Part Two

::: {.panel-tabset}

## Solution

```{r}
#| label: 2015 - day 5 - part 2

has_couple_twice <- function(string) {
    str_detect(string = string, pattern = "[a-z]*([a-z]{2})[a-z]*\\1[a-z]*")
}

has_az_any_az <- function(string) {
    str_detect(string = string, pattern = "([a-z])[a-z]\\1")
}

is_nice_new <- function(string) {
    has_couple_twice(string) &
    has_az_any_az(string)
}

nice_new <- input |> 
    mutate(couple_twice = map_lgl(.x = original, .f = has_couple_twice),
           az_any_az    = map_lgl(.x = original, .f = has_az_any_az),
           nice_new     = map_lgl(.x = original, .f = is_nice_new))

nice_new |> 
    summarise(total_nice = sum(nice_new)) |> 
    pull(total_nice) |> 
    cat()
```

## Full Table

```{r}
#| label: 2015 - day 5 - part 2 full table
#| echo: false

rmarkdown::paged_table(nice_new)
```

:::
